name: test
on:
  push:
    branches:
      - "main"
jobs:
  linux-x64-gnu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: |
          corepack enable
          corepack prepare --activate
      - run: yarn install
      - run: node index.mjs
  linux-arm64-gnu:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: |
          corepack enable
          corepack prepare --activate
      - run: yarn install
      - run: node index.mjs
  windows-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: |
          corepack enable
          corepack prepare --activate
      - run: yarn install
      - run: node index.mjs
  macos-intel:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: |
          corepack enable
          corepack prepare --activate
      - run: yarn install
      - run: node index.mjs
  macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: |
          corepack enable
          corepack prepare --activate
      - run: yarn install
      - run: node index.mjs
